CREATE COLUMN TABLE "NEO_<YOUR_SCHEMA_ID>"."MANAGERS" ("ID" INTEGER CS_INT NOT NULL,"NAME" VARCHAR(100),"ADDRESS" VARCHAR(1000),"REGION" VARCHAR(5),"BUDGET" DOUBLE CS_DOUBLE,PRIMARY KEY ("ID"))  
                
CREATE TYPE "NEO_<YOUR_SCHEMA_ID>"."manager/SCRIPTVIEW/proc/tabletype/VAR_OUT" AS TABLE ("ID" INTEGER CS_INT,"NAME" VARCHAR(100) CS_STRING,"REGION" VARCHAR(5) CS_STRING,"BUDGET" DOUBLE CS_DOUBLE,"BUDGET_PERCENTAGE_SHARE" DOUBLE CS_DOUBLE)
